In [1]:
import numpy as np

In [390]:
x = np.array([[4, 7, 5], 
              [9, 1, 2],
              [3, 6, 8]   
              ])
y = np.array([1, 2, 3])
x, y

(array([[4, 7, 5],
        [9, 1, 2],
        [3, 6, 8]]),
 array([1, 2, 3]))

In [391]:
y[x.argsort(axis = 1)]

array([[1, 3, 2],
       [2, 3, 1],
       [1, 2, 3]])

In [22]:
tmp = np.hstack((x[:, 1].reshape(-1, 1), y.reshape(-1, 1)))
tmp

array([[7, 1],
       [9, 2],
       [6, 3]])

In [398]:
l = np.array(np.array(range(10)) + np.zeros(13).reshape(-1, 1))
l

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [399]:
7 - l

array([[ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.],
       [ 7.,  6.,  5.,  4.,  3.,  2.,  1.,  0., -1., -2.]])

In [23]:
tmp[tmp[:, 0].argsort()]

array([[6, 3],
       [7, 1],
       [9, 2]])

In [26]:
for i in range (1, y.shape[0]):
   print(i) 

1
2


In [44]:
_, counts = np.unique(y, return_counts = True)
p = counts/y.shape[0]
p

array([0.27272727, 0.27272727, 0.45454545])

In [50]:
H = -np.sum(p * np.log(p)/np.log(2))
H

1.5394847569315018

In [52]:
np.log(p)

array([-1.29928298, -1.29928298, -0.78845736])

In [54]:
np.log(0.2)

-1.6094379124341003

In [67]:
idx = np.asarray([2, 3])
idx = idx.reshape(1, -1)
y = y.reshape(-1, 1)

In [71]:
y.argmin()

0

In [72]:
z = np.zeros(10)

In [79]:
clss, counts = np.unique(z, return_counts=True)
clss, counts

(array([0.]), array([10], dtype=int64))

In [82]:
np.sum(y ** 2)

60

In [356]:
def impurity1(p):
    return 1 - np.sum(p ** 2)


In [378]:
def find_threshold1(x, y):
    x = np.asarray(x)
    y = np.asarray(y)
    R = y.size
    n_class, counts = np.unique(y, return_counts = True)
    H = impurity1(counts/R)
    max_Q = 0
    max_idx = [0, 0, 0]
    for i in range (x.shape[1]):
        feature_response = np.hstack((x[:, i].reshape(-1, 1), y.reshape(-1, 1)))
        feature_response = feature_response[feature_response[:, 0].argsort()]
        Rl = 0
        Rr = R
        counts_left = np.zeros(counts.size)
        counts_right = np.copy(counts)
        for j in range (0, R - 1):
            Rl += 1
            Rr -= 1
            idx = feature_response[j, 1]
            counts_left[int(idx) == n_class] += 1
            counts_right[int(idx) == n_class] -= 1
            Hl = impurity1(counts_left/Rl)
            Hr = impurity1(counts_right/Rr)
            Q = H - (Hl * Rl / R) - (Hr * Rr / R)
            if Q > max_Q:
                max_Q = Q
                max_idx[0] = i
                max_idx[1] = np.mean(feature_response[j:j+2, 0])
                max_idx[2] = max_Q
    return max_idx


In [379]:
x = np.array([[2, 4, 3, 1, 5],[3,7,5,2,1]])
y = np.array([0,1,1,0,1])

In [380]:
arg_sort_x = np.sort(x, axis = 0)
arg_sort_x.T

array([[2, 3],
       [4, 7],
       [3, 5],
       [1, 2],
       [1, 5]])

In [381]:
x = x.T
x

array([[2, 3],
       [4, 7],
       [3, 5],
       [1, 2],
       [5, 1]])

In [382]:
arg_sort_y = y[x.argsort(axis = 0)]
R = y.size
n_class, counts = np.unique(y, return_counts = True)
H = impurity1(counts/R)
arg_sort_y

array([[0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1]])

In [383]:
def count_q(y):
    max_Q = 0
    max_idx = [0, 0]
    for j in range (0, R - 1):
        n_class_left, counts_left = np.unique(y[0:j+1], return_counts = True)
        n_class_right, counts_right = np.unique(y[j+1:y.size], return_counts = True)
        Rl = j + 1
        Rr = y.size - Rl
        Hl = impurity1(counts_left/Rl)
        Hr = impurity1(counts_right/Rr)
        Q = H - (Hl * Rl / R) - (Hr * Rr / R)
        if Q > max_Q:
            max_Q = Q 
            max_idx[0] = Q
            max_idx[1] = j

    return max_idx 

result = np.apply_along_axis(count_q, 0, arg_sort_y)

In [384]:
find_threshold1(x, y)

[0, 2.5, 0.48]

In [385]:
result = result.T


In [386]:
result

array([[0.48      , 1.        ],
       [0.21333333, 2.        ]])

In [372]:
idx = np.argmax(result[0])
res = result[1][idx]
res

1.0